### ISSUE TITLE
Add a generic framework for sending out reminders of dates

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/EfileProxyServer#1]

**Comment by BryceStevenWilley** [comment]
I moved this issue over early, and in hindsight it really shouldn't have been. We are already sending out emails when we get responses, but I think we need to be live more if we want to send more specific reminders. And tbh the better platform for that is docassemble, since each dev user of the proxy server will have their own criteria to send follow ups. Going to close, can revisit if we need to eventually send callbacks to the DA servers that originally sent us the info so they know when the court has responded, etc.
