### ISSUE TITLE
Consider returning the original XML for certain API endpoints - e.g., get_case and get_cases

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/EfileProxyServer#27]
The transformed JSON moves around some keys in a way that makes the data a bit less clear. This shouldn't hold up release though, especially as we're not making extensive use of the ECF representation other than for sending data--we just pull out a couple of keys for searches etc.

**Comment by BryceStevenWilley** [comment]
Since this was made, we have started parsing a lot more out of the responses, but a lot of them are still returned as JSON. The main thing holding this up is that it's difficult to get the JAX-RS to transform between JSON like values and XML like input and output, and the XML output and input is much harder to handle on the Java side, as we have to make many more boilerplate classes, that would essentially duplicate a lot of existing work (all because XML doesn't have a notion of a list or map, so returning more than one thing needs a special type for each thing, no generics).

Given our primary use case is still docassemble, I'd say that we're fine there. It might be a bit more difficult for REST API users to get what they need out of more complicated things, like the full details of a case, but we can shown it's still possible (and TBH would be just as complicated in XML, the complicated part is just integrating a heavy XML-schema reader in your software). But since we don't have many (i.e. any) REST API users yet, I'm going to push this to after prod. I expect this might be the first thing that bumps us to a version 2.0, but we do need some example users to know the right way to do things.

**Comment by BryceStevenWilley** [comment]
This is a thing I'm wrangling with now with ECF5. Essentially, we will likely need to work with ECF 4 and ECF 5 jurisdictions at the same time, and IMO, it's a very bad idea to try to expect all of the client implementations to compare and convert between the two, especially when they don't know which jurisdiction is using which. Our proxy wouldn't be very useful if we just continued doing what we're currently doing and passing through either the XML or the JSON-ized version of the XML.

We're going to need to have a (hopefully) relatively standard that we can put all of the data that we're using from ECF 4 stuff on docassemble and put it in our own JSON data type. It can be extensible in a python-dict sense, so if something the client is looking for is there, it can use it.

Technically this is a different issue, so I'll close this one and will open a new one to link back to here.
