### ISSUE TITLE
Add a 404 endpoint

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/EfileProxyServer#35]

**Comment by BryceStevenWilley** [comment]
What exactly do we mean when we say 404 endpoint here? It's primarily a REST server, not HTML, and we already return 404s for things that don't exist.

**Comment by nonprofittechy** [comment]
Hard to recall. I think I opened this because I couldn't tell if the server was offline or if there was no response to the query or I had the wrong route.

If we return a 404 for an invalid route we're okay.

**Comment by BryceStevenWilley** [comment]
Ah, gotcha, I remember now. Partially correct URLs like `https://efile.com:9000/codes/` would return 404s instead of doing the RESTful thing of telling you about the other URLs that you could query, like `/codes/{court}`, etc. That should be fixed in https://github.com/SuffolkLITLab/EfileProxyServer/pull/96

**Comment by BryceStevenWilley** [comment]
Should be fixed now that #96 is in.
